# Generated by Django 2.2.15 on 2021-05-28 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Show',
            new_name='Shows',
        ),
    ]
