# Generated by Django 2.2.15 on 2021-05-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20210528_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
